# Generated by Django 4.2 on 2024-08-15 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('rus', models.CharField(max_length=100, verbose_name='Кнопка (русский)')),
                ('heb', models.CharField(max_length=100, verbose_name='Кнопка (иврит)')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'кнопка',
                'verbose_name_plural': 'кнопки',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник телеграм')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'работодатель',
                'verbose_name_plural': 'работодатель',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=200, unique=True, verbose_name='TG id фото')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('rus', models.CharField(max_length=100, verbose_name='Профессия (русский)')),
                ('heb', models.CharField(max_length=100, verbose_name='Профессия (иврит)')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'профессия',
                'verbose_name_plural': 'профессии',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('rus', models.TextField(max_length=1024, verbose_name='Текст (русский)')),
                ('heb', models.TextField(max_length=1024, verbose_name='Текст (иврит)')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'тексты',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('target', models.CharField(choices=[(1, 'Работник'), (2, 'Работодатель')], max_length=10, verbose_name='Тип пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник телеграм')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('passport_photo_tg_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='TG id паспорта')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('min_salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата (от ₪/час)')),
                ('notifications', models.BooleanField(default=False, verbose_name='Подписан на уведомления?')),
                ('is_searching', models.BooleanField(default=True, verbose_name='В поисках работы?')),
                ('profile_complete', models.BooleanField(default=False, verbose_name='Профиль заполнен?')),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('objects', models.ManyToManyField(blank=True, related_name='objects_photos', to='core.objectphoto', verbose_name='Фото объектов')),
                ('occupations', models.ManyToManyField(blank=True, related_name='users', to='core.occupation', verbose_name='Профессии')),
                ('passport_photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото паспорта')),
            ],
            options={
                'verbose_name': 'работник',
                'verbose_name_plural': 'работники',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=5, verbose_name='Оценка')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reviews', to='core.employer', verbose_name='Работодатель, получивший отзыв')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaved_reviews', to='core.worker', verbose_name='Сотрудник, оставивший отзыв')),
            ],
            options={
                'verbose_name': 'отзыв работника',
                'verbose_name_plural': 'отзывы работников',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата (от ₪/час)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('notifications', models.BooleanField(default=False, verbose_name='Подписан на уведомления?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer', verbose_name='Работодатель')),
                ('occupations', models.ManyToManyField(blank=True, related_name='jobs', to='core.occupation', verbose_name='Профессии')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmployerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=5, verbose_name='Оценка')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaved_reviews', to='core.employer', verbose_name='Работодатель, оставивший отзыв')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reviews', to='core.worker', verbose_name='Сотрудник, получивший отзыв')),
            ],
            options={
                'verbose_name': 'отзыв работодателя',
                'verbose_name_plural': 'отзывы работодателей',
                'ordering': ('-created_at',),
            },
        ),
    ]
