# Generated by Django 4.2 on 2024-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='heb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кнопка (иврит)'),
        ),
        migrations.AlterField(
            model_name='button',
            name='rus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кнопка (русский)'),
        ),
        migrations.AlterField(
            model_name='text',
            name='heb',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст (иврит)'),
        ),
        migrations.AlterField(
            model_name='text',
            name='rus',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст (русский)'),
        ),
    ]
