# Generated by Django 4.2 on 2024-08-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_button_heb_alter_button_rus_alter_text_heb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='profile_complete',
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
