# Generated by Django 4.2 on 2024-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_objects_worker_objects_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_rus',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='worker',
            name='about_heb',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='О себе (иврит)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Аккаунт подтвержден?'),
        ),
    ]
