# Generated by Django 4.2 on 2024-08-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_description_rus_worker_about_heb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelForEmployers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('is_active', models.BooleanField(default=True, verbose_name='Участвует в рассылке?')),
            ],
            options={
                'verbose_name': 'канал для работодателей',
                'verbose_name_plural': 'каналы для работодателей (с сотрудниками)',
            },
        ),
        migrations.CreateModel(
            name='ChannelForWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('is_active', models.BooleanField(default=True, verbose_name='Участвует в рассылке?')),
            ],
            options={
                'verbose_name': 'канал для работников',
                'verbose_name_plural': 'каналы для работников (с вакансиями)',
            },
        ),
    ]
