# Generated by Django 4.2 on 2024-08-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_job_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCooperationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(blank=True, default=None, null=True)),
                ('is_proceeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_proposals', to='core.employer', verbose_name='Работодатель, получивший запрос')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.job', verbose_name='Вакансия, вызвавшая запрос')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_proposals', to='core.worker', verbose_name='Работник, запросивший сотрудничество')),
            ],
            options={
                'verbose_name': 'предложение о сотрудничестве от работника',
                'verbose_name_plural': 'предложения о сотрудничестве от работников',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='EmployerCooperationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(blank=True, default=None, null=True)),
                ('is_proceeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_proposals', to='core.employer', verbose_name='Работодатель, запросивший сотрудничество')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_proposals', to='core.worker', verbose_name='Работник, получивший запрос')),
            ],
            options={
                'verbose_name': 'предложение о сотрудничестве от работодателей',
                'verbose_name_plural': 'предложения о сотрудничестве от работодателей',
                'ordering': ('-updated_at',),
            },
        ),
    ]
