# Generated by Django 4.2 on 2024-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workercooperationproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerreview',
            name='review_rus',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв (иврит)'),
        ),
        migrations.AddField(
            model_name='workerreview',
            name='review_heb',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв (иврит)'),
        ),
        migrations.AlterField(
            model_name='employercooperationproposal',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Принят?'),
        ),
        migrations.AlterField(
            model_name='employercooperationproposal',
            name='is_proceeded',
            field=models.BooleanField(default=False, verbose_name='Отправлен в админ чат?'),
        ),
        migrations.AlterField(
            model_name='employerreview',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв (русский)'),
        ),
        migrations.AlterField(
            model_name='workercooperationproposal',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Принят?'),
        ),
        migrations.AlterField(
            model_name='workercooperationproposal',
            name='is_proceeded',
            field=models.BooleanField(default=False, verbose_name='Отправлен в админ чат?'),
        ),
        migrations.AlterField(
            model_name='workerreview',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв (русский)'),
        ),
    ]
