# Generated by Django 4.2 on 2024-08-23 11:23

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_employerreview_review_rus_workerreview_review_heb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('1', 'Индивидуальное'), ('2', 'Всем работникам'), ('3', 'Всем работодателям'), ('4', 'Всем пользователям')], max_length=30, verbose_name='Тип уведомления')),
                ('text_rus', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст уведомления (русский)')),
                ('text_heb', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст уведомления (иврит)')),
                ('notify_time', models.DateTimeField(blank=True, help_text='Указывается в UTC (-3 от МСК).', null=True, verbose_name='Время уведомления')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Рассылка валидна?')),
                ('started', models.BooleanField(default=False, verbose_name='Рассылка началась?')),
                ('notified', models.BooleanField(blank=True, default=None, null=True, verbose_name='Уведомлен')),
                ('user', models.ForeignKey(blank=True, help_text='Учитывается только если выбран тип "индивидуальное"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'уведомление пользователей',
                'verbose_name_plural': 'уведомления пользователей',
                'ordering': ('-notify_time',),
            },
        ),
        migrations.CreateModel(
            name='LinkButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_rus', models.CharField(blank=True, max_length=50, null=True)),
                ('text_heb', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(max_length=1024)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'кнопка с ссылкой',
                'verbose_name_plural': 'кнопки с ссылками',
            },
        ),
    ]
