# Generated by Django 4.2 on 2024-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkbutton',
            options={'ordering': ('my_order',), 'verbose_name': 'кнопка с ссылкой', 'verbose_name_plural': 'кнопки с ссылками'},
        ),
        migrations.AddField(
            model_name='linkbutton',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
