# Generated by Django 4.2 on 2024-08-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_linkbutton_options_linkbutton_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('my_order', '-notify_time'), 'verbose_name': 'уведомление пользователей', 'verbose_name_plural': 'уведомления пользователей'},
        ),
        migrations.AddField(
            model_name='notification',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='linkbutton',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='notifications.notification', verbose_name='Уведомление'),
        ),
    ]
