# Generated by Django 4.2 on 2024-08-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_my_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-notify_time',), 'verbose_name': 'уведомление пользователей', 'verbose_name_plural': 'уведомления пользователей'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='my_order',
        ),
    ]
