# Generated by Django 4.2 on 2024-08-23 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkbutton',
            name='link',
            field=models.CharField(max_length=1024, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='linkbutton',
            name='text_heb',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Текст (иврит)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkbutton',
            name='text_rus',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Текст (русский)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(help_text='Указывается в UTC (-3 от МСК).', verbose_name='Время уведомления'),
        ),
    ]
