# Generated by Django 4.2 on 2024-08-23 12:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('notifications', '0005_alter_linkbutton_link_alter_linkbutton_text_heb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
    ]
