# Generated by Django 4.2 on 2024-08-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='success_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='total_send_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linkbutton',
            name='link',
            field=models.CharField(help_text='Обязательно должна содержать "https://"', max_length=1024, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notified',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Успешно?'),
        ),
    ]
